spring:
  application:
    name: AuthorzationServerApp
  profiles:
    active: dev

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto:     update
      jdbc:
        lob:
          non_contextual_creation: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/auth-db?ApplicationName=AuthorzationServerApp
    username: data&&Admin1User_aut
    password: 'numeryx&&2019W'
    driver-class-name: org.postgresql.Driver

#  cloud:
#    consul:
#      discovery:
#        fail-fast: false

  session:
    store-type: none


server:
  address: 0.0.0.0
  port: 9000
#  session:
#    timeout: 30
security:
  oauth2:
    authorization:
    client:
      client-id: client_numeryx
      client-secret: secret_numeryx
      grant-type: password
    tokenTimeout: 950400
    resource:
      id: authorization-service
  jwt:
    key-store-password: numeryx2020
    key-pair-alias: num-oauth-jwt
    key-pair-password: numeryx2020
    public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArk5gHy9uIy0IGikp3ADWAn3wY5cms+6QTonWmeUmvKKR4Se37yar4HgNC02tClWtW1XObb8OsWzVnqggSPvBBik93OXXGl0wzDReVXRG2lJC4Y0I4OpUrEbZKK8FsrIifJvCheTBS9fBkjCnJCN+ZlsYHtyRoiKtPm5nHoHuqbIPSFVUUsH8DLYu7ZdxXQHsxp64PFPtfym3EjRX6eX4Kgmnt++b7a2bImFZMUQksVl++RKmS5K7vZqdxEVPMWlowP3ZjHd0F9VSjjxwcjv4qsnq5zZIp3UR/n7v6WSKGQ0p8JdwGYxqEBYRJIRyGy5rrSpZIoWRAuEX0CEFJwVhPwIDAQAB
    private-key: MIIDgTCCAmmgAwIBAgIERMw49TANBgkqhkiG9w0BAQsFADBxMRAwDgYDVQQGEwd0dW5pc2lhMQ4wDAYDVQQIEwV0dW5pczEOMAwGA1UEBxMFdHVuaXMxGzAZBgNVBAoTEm51bWVyeXggaW5ub3ZhdGlvbjEQMA4GA1UECxMHbnVtZXJ5eDEOMAwGA1UEAxMFd2FsaWQwHhcNMTkxMjEwMTYwODUwWhcNMjAwMzA5MTYwODUwWjBxMRAwDgYDVQQGEwd0dW5pc2lhMQ4wDAYDVQQIEwV0dW5pczEOMAwGA1UEBxMFdHVuaXMxGzAZBgNVBAoTEm51bWVyeXggaW5ub3ZhdGlvbjEQMA4GA1UECxMHbnVtZXJ5eDEOMAwGA1UEAxMFd2FsaWQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCuTmAfL24jLQgaKSncANYCffBjlyaz7pBOidaZ5Sa8opHhJ7fvJqvgeA0LTa0KVa1bVc5tvw6xbNWeqCBI+8EGKT3c5dcaXTDMNF5VdEbaUkLhjQjg6lSsRtkorwWysiJ8m8KF5MFL18GSMKckI35mWxge3JGiIq0+bmcege6psg9IVVRSwfwMti7tl3FdAezGnrg8U+1/KbcSNFfp5fgqCae375vtrZsiYVkxRCSxWX75EqZLkru9mp3ERU8xaWjA/dmMd3QX1VKOPHByO/iqyernNkindRH+fu/pZIoZDSnwl3AZjGoQFhEkhHIbLmutKlkihZEC4RfQIQUnBWE/AgMBAAGjITAfMB0GA1UdDgQWBBT0BnQSe7549w3fITUP+Tv7cCXSxDANBgkqhkiG9w0BAQsFAAOCAQEAganMuSSwnVboz3/Esrw7IR+aq2TXiPZ6Hd69Sg6Kq2m7qLxqnuDxGRwebTJdIDuKB0jZKmbITgw+rj1g8VA0B1qobeq48x2XlyNlooIdanP60Rag5rLiWGoK+XvvPUNV3CVfZjfLSEl5qCgZDWUcDALaA3qp7sSWsQZZYpw0FzJM4PXmQdZq9qTKoV0CBx+68230xiEvog6y7qBPl3ZUgIBJHdFzJXG0W5mLQX7rxhg6ZgBvsg8HZ4VoIbzxyVTvS4Sun4XIqabIGfLZKZ8D+xnBRbiJojlyxWzmceGZ7Sf31FnuoXdoH866ZE/92Uob7dc68+wcyFoK6mjC+kDuAA==
ribbon:
  eager-load:
    enabled: true
#endpoints:
#  health:
#    enabled: true

credentials:
  super-admin-user-login: super_admin@yopmail.com
  super-admin-user-password: numeryx2020
config:
  connector:
    token: eyJ4NXQiOiJOMkpqTWpOaU0yRXhZalJrTnpaalptWTFZVEF4Tm1GbE5qZzRPV1UxWVdRMll6YzFObVk1TlEiLCJraWQiOiJNREpsTmpJeE4yRTFPR1psT0dWbU1HUXhPVEZsTXpCbU5tRmpaalEwWTJZd09HWTBOMkkwWXpFNFl6WmpOalJoWW1SbU1tUTBPRGRpTkRoak1HRXdNQV9SUzI1NiIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiJpYW1pcmEiLCJhdXQiOiJBUFBMSUNBVElPTiIsImF1ZCI6ImRLYjZGNFp5U0dFS3I0YWJaQTZXMjNGVVBPTWEiLCJuYmYiOjE2OTUzNzEzNjgsImF6cCI6ImRLYjZGNFp5U0dFS3I0YWJaQTZXMjNGVVBPTWEiLCJzY29wZSI6ImRlZmF1bHQiLCJpc3MiOiJodHRwczpcL1wvbG9jYWxob3N0Ojk0NDNcL29hdXRoMlwvdG9rZW4iLCJleHAiOjE2OTYwMDEzNjgsImlhdCI6MTY5NTM3MTM2OCwianRpIjoiNDRkNWExYmYtZjVmOC00YWUxLTgxNGQtNTBhMTJkODNhODY3In0.XQRtNMM40x4hhFWQbR1kR0bb_sLwZVlYUqdDg7Yz91H6N-xi8gYTldHgvyu4DXG1WEqorWhd0eTQjZtjSxvXDtoEEy6bBv6_i6_HqqVChl6ZjT92ZCg3Es42jzn2nUdg08Dp0dREUBmGag-Q8Qves4HDgueOU1dQ2eeywjCY10U9SMi_LD9lXgU0Ia1359Fv75ciiShkj93QH8AMvfsN04d9n6jx2dQLTyJ4DJVr66xvSpkp-09DDdd6SxKccl2_ldAjafAPDV0LbsLolGtxXXd9ACPfNZNWsKusVu1X8BDaBryQO4ieLLoGngOOwncVpVFZHJtqr8DM9FbtfKYUXA

feign:
  client:
    config:
      default:
        connectTimeout: 50000
        readTimeout: 50000
        loggerLevel: basic
      apis:
        notification: http://localhost:8002
        minio: http://localhost:8003
        connector: http://localhost:3001
logging:
  pattern:
    console: " %d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger{36}.%M - %msg%n"
  level:
    ROOT: debug
    com.numeryx.AuthorizationServiceApplication: DEBUG
    org.springframework: INFO
    org.hibernate: INFO
    liquibase: INFO
mail:
  host: smtp.gmail.com
  port: 587
  username: amiraba.wissalo@gmail.com
  password: numeryx2020
  protocol: smtp
  tls: true
  properties.mail.smtp:
    auth: true
    starttls.enable: true
    ssl.trust: smtp.gmail.com
    socketFactory.class: javax.net.ssl.SSLSocketFactory
    socketFactory.fallback: false

urls:
  front-office-port: http://localhost:4201
  back-office-port: http://localhost:4200

LoadOrigins : http://localhost:4201,http://localhost:4200, http://localhost:8003
