spring:
  jpa:
    hibernate:
      ddl-auto:     update

config:
  oauth2:
    accessTokenUri: http://localhost:9000/oauth/token
  path-jks: C:\Windows\System32\drivers\etc\ssl\num-auth.jks
context: http://localhost:4200/

websocket:
  relay-host: rabbitmq
  relay-port: 61613
  client-login: userWorkflowAndforms
  client-passcode: ntf&&20NUMeRyX20

LoadOrigins : http://localhost:4201,http://localhost:4200
hosts-url:
  frontoffice: http://localhost:4201/
  backoffice: http://localhost:4200/
  develop: 'true'
  origins: http://localhost:4200,http://localhost:4201,http://localhost:9000,http://localhost:8002,http://localhost:8003,http://localhost:8007,http://localhost:8008,
  swagger-api: http://localhost:9000,http://localhost:8002,http://localhost:8003,http://localhost:8007,http://localhost:8008
