spring:
  application:
    name: NotificationApp 
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/notif-db
    username: data&&Admin1User_notif
    password: numeryx&&2019W
    driver-class-name: org.postgresql.Driver
  cloud:
    consul:
      discovery:
        fail-fast: false
  thymeleaf:
    cache: false
  mail:
    host: smtp.office365.com
    username: pole-dev@numeryx.fr #numeryx.integration.mailing@gmail.com
    password: Numeryx@@2022** #numeryxIntegration
    port: 587
    properties:
      mail:
        protocol: smtp
        tls: true
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.office365.com

  session:
    store-type: none
  rabbitmq:
    host: localhost
    port: 61613
    username: userNotif
    password: ntf&&20NUMeRyX20
    ssl:
      enabled: false
 #    key-store: C:\Windows\System32\drivers\etc\num-auth.jks
   #   key-store-password: numeryx2020
server:
  address: 0.0.0.0
  port: 8002
  max-http-header-size: 10000000
#  session:
#    timeout: 30
security:
  oauth2:
    resource:
      id: notification-service
    client:
      client-id: client_numeryx
      client-secret: secret_numeryx
      grant-type: password
  jwt:
    key-store-password: numeryx2020
    key-pair-alias: num-oauth-jwt
    key-pair-password: numeryx2020
    public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArk5gHy9uIy0IGikp3ADWAn3wY5cms+6QTonWmeUmvKKR4Se37yar4HgNC02tClWtW1XObb8OsWzVnqggSPvBBik93OXXGl0wzDReVXRG2lJC4Y0I4OpUrEbZKK8FsrIifJvCheTBS9fBkjCnJCN+ZlsYHtyRoiKtPm5nHoHuqbIPSFVUUsH8DLYu7ZdxXQHsxp64PFPtfym3EjRX6eX4Kgmnt++b7a2bImFZMUQksVl++RKmS5K7vZqdxEVPMWlowP3ZjHd0F9VSjjxwcjv4qsnq5zZIp3UR/n7v6WSKGQ0p8JdwGYxqEBYRJIRyGy5rrSpZIoWRAuEX0CEFJwVhPwIDAQAB
    private-key: MIIDgTCCAmmgAwIBAgIERMw49TANBgkqhkiG9w0BAQsFADBxMRAwDgYDVQQGEwd0dW5pc2lhMQ4wDAYDVQQIEwV0dW5pczEOMAwGA1UEBxMFdHVuaXMxGzAZBgNVBAoTEm51bWVyeXggaW5ub3ZhdGlvbjEQMA4GA1UECxMHbnVtZXJ5eDEOMAwGA1UEAxMFd2FsaWQwHhcNMTkxMjEwMTYwODUwWhcNMjAwMzA5MTYwODUwWjBxMRAwDgYDVQQGEwd0dW5pc2lhMQ4wDAYDVQQIEwV0dW5pczEOMAwGA1UEBxMFdHVuaXMxGzAZBgNVBAoTEm51bWVyeXggaW5ub3ZhdGlvbjEQMA4GA1UECxMHbnVtZXJ5eDEOMAwGA1UEAxMFd2FsaWQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCuTmAfL24jLQgaKSncANYCffBjlyaz7pBOidaZ5Sa8opHhJ7fvJqvgeA0LTa0KVa1bVc5tvw6xbNWeqCBI+8EGKT3c5dcaXTDMNF5VdEbaUkLhjQjg6lSsRtkorwWysiJ8m8KF5MFL18GSMKckI35mWxge3JGiIq0+bmcege6psg9IVVRSwfwMti7tl3FdAezGnrg8U+1/KbcSNFfp5fgqCae375vtrZsiYVkxRCSxWX75EqZLkru9mp3ERU8xaWjA/dmMd3QX1VKOPHByO/iqyernNkindRH+fu/pZIoZDSnwl3AZjGoQFhEkhHIbLmutKlkihZEC4RfQIQUnBWE/AgMBAAGjITAfMB0GA1UdDgQWBBT0BnQSe7549w3fITUP+Tv7cCXSxDANBgkqhkiG9w0BAQsFAAOCAQEAganMuSSwnVboz3/Esrw7IR+aq2TXiPZ6Hd69Sg6Kq2m7qLxqnuDxGRwebTJdIDuKB0jZKmbITgw+rj1g8VA0B1qobeq48x2XlyNlooIdanP60Rag5rLiWGoK+XvvPUNV3CVfZjfLSEl5qCgZDWUcDALaA3qp7sSWsQZZYpw0FzJM4PXmQdZq9qTKoV0CBx+68230xiEvog6y7qBPl3ZUgIBJHdFzJXG0W5mLQX7rxhg6ZgBvsg8HZ4VoIbzxyVTvS4Sun4XIqabIGfLZKZ8D+xnBRbiJojlyxWzmceGZ7Sf31FnuoXdoH866ZE/92Uob7dc68+wcyFoK6mjC+kDuAA==
ribbon:
  eager-load:
    enabled: true
#endpoints:
#  health:
#    enabled: true

logging:
  pattern:
    console: " %d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger{36}.%M - %msg%n"
  level:
    com.numeryx.notification: DEBUG
    org.springframework: INFO
    org.hibernate: INFO
    liquibase: INFO
feign:
  client:
    config:
      default:
        connectTimeout: 50000
        readTimeout: 50000
        loggerLevel: basic
      apis:
        auth: http://localhost:9000/
        workflow: http://localhost:8008/
websocket:
  relay-host: localhost
  relay-port: 61613
  client-login: userNotif
  client-passcode: ntf&&20NUMeRyX20
config:
  oauth2:
    path-jks: C:\Windows\System32\drivers\etc\ssl\num-auth.jks
    accessTokenUri: http://localhost:9000/oauth/token
context: http://localhost:4200/
contextFrontOffice:  http://localhost:4201/

LoadOrigins : http://localhost:4201,http://localhost:4200
hosts-url:
  frontoffice: http://localhost:4201/
  backoffice: http://localhost:4200/ 
  develop: 'true'
  origins: http://localhost:4200,http://localhost:4201,http://localhost:9000,http://localhost:8002,http://localhost:8003,http://localhost:8007,http://localhost:8008,
  swagger-api: http://localhost:9000,http://localhost:8002,http://localhost:8003,http://localhost:8007,http://localhost:8008
